# Generated by Django 6.1.2 on 2026-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('DENIED_EXPIRED', 'Denied - Pass Expired or Not Started'), ('DENIED_UNREGISTERED', 'Denied - Not in System'), ('ERROR', 'Error - OCR Failed')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='No spaces, e.g., PB02AB1234', max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff')], default='STUDENT', max_length=20)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
